services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_SESSION_TOKEN

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
