apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikube-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haikube-frontend
  template:
    metadata:
      labels:
        app: haikube-frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/haikube-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://haikube-backend.default.svc.cluster.local:5000"
