name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-cicd.yaml'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint-test-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint backend
        working-directory: ./backend
        run: |
          go vet ./...
          golint ./... || true

      - name: Test backend
        working-directory: ./backend
        run: go test ./...

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push backend Docker image
        working-directory: ./backend
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG -t ${{ vars.ECR_REPOSITORY_BACKEND }}:latest .
          docker tag ${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG
          docker tag ${{ vars.ECR_REPOSITORY_BACKEND }}:latest $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:latest
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:latest
