name: CI/CD for Frontend and Backend

on:
  push:
    branches: [dev]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint backend
        working-directory: ./backend
        run: |
          go vet ./...
          golint ./... || true

      - name: Lint frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint || true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Test backend
        working-directory: ./backend
        run: go test ./...

      - name: Test frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push backend
        working-directory: ./backend
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG -t ${{ vars.ECR_REPOSITORY_BACKEND }}:latest .
          docker tag ${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG
          docker tag ${{ vars.ECR_REPOSITORY_BACKEND }}:latest $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:latest
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_BACKEND }}:latest

      - name: Build & push frontend
        working-directory: ./frontend
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY_FRONTEND }}:$IMAGE_TAG -t ${{ vars.ECR_REPOSITORY_FRONTEND }}:latest .
          docker tag ${{ vars.ECR_REPOSITORY_FRONTEND }}:$IMAGE_TAG $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_FRONTEND }}:$IMAGE_TAG
          docker tag ${{ vars.ECR_REPOSITORY_FRONTEND }}:latest $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_FRONTEND }}:latest
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_FRONTEND }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_FRONTEND }}:latest
