# .github/workflows/lint.yml
name: Lint Go Code

on:
  workflow_dispatch: 

  push:
    branches:
      - dev
    paths:
      - '**.go'

  pull_request:
    branches:
      - dev
    paths:
      - '**.go'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24 # or your version

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/cmd/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      #- name: Run linter
      #  run: golangci-lint run ./...
